version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - HOST=0.0.0.0
    command: ['npm', 'start']
    stdin_open: true
    tty: true
