version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: []
    environment:
      - HOST=0.0.0.0
    command: ['yarn', 'start']
    stdin_open: true
    tty: true
