version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - HOST=0.0.0.0
    command: ['./bin/dev']
    stdin_open: true
    tty: true
