version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker build . -t app
      - run:
          name: Build app
          command: |
            docker run -it app ./bin/build
      - run:
          name: Export image
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
       - save_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar
  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar
      - run:
          name: Restore Image
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run: docker images
      - run:
          name: Deploy app
          command: |
            docker run -it app ./bin/deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: tryal-sam
