version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build . -t app
      - run:
          name: Export image
          command: |
            mkdir -p ~/caches
            docker save app:latest -o ~/caches/app-latest.tar
      - save_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/app-latest.tar
  deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/app-latest.tar
      - run:
          name: Restore Image
          command: |
            set +o pipefail
            docker load -i ~/caches/app-latest.tar | true
      - run: docker images
      - run: docker build . -t app
      - run: docker run -it app ./bin/build
      - run: docker run -it app ./bin/deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: tryal-sam
